import { Provider } from "./api/Provider";
import { Header } from "./components/Header"
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {/* Header */}
          <Header/>
          {/* Navbar */}
          <Navbar/>
          {/* Search */}
          {children}
        </Provider>
      </body>
    </html>
  )
}
